# Header
menu:
  主页: /
  所有文章: /archives
  html5: /tags/html5
  JS: /tags/ReactJs
  CSS: /tags/css


# SubNav
subnav:
  github: "https://github.com/genie88"
  #weibo: ""
  #rss: "#"
  #zhihu: ""
  #douban: "#"
  mail: "genie88@163.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: "/img/avatar.jpg"
#是否开启分享
share: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  React中文网: http://react-china.org/
  大前端: http://daqianduan.com

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: "和设计师一样细腻,和程序员一样严谨;游走在设计师和工程师之间,游刃于用户体验和技术实现之间,斡旋在用户利益和商业利益之间。"
